version: "3.1"

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        env_file: .env
        networks:
            - transcendence
        expose:
            - "5432"

    frontend:
        image: frontend
        container_name: frontend
        build:
            context: ./srcs/frontend
            args:
                - VITE_CLIENT_ID=${VITE_CLIENT_ID}
                - VITE_API_URL=${VITE_API_URL}
                - VITE_AUTH_URL=${VITE_AUTH_URL}
        depends_on:
            - backend
        networks:
            - transcendence
        ports:
            - "4173:4173"

    backend:
        image: backend
        container_name: backend
        build: ./srcs/backend
        restart: always
        env_file: .env
        networks:
            - transcendence
        depends_on:
            - postgres
        links:
            - postgres
        ports:
            - "3000:3000"

networks:
    transcendence:
