version: "3.8"

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - transcendence

    frontend:
        image: frontend
        container_name: frontend
        build:
            context: ./srcs/frontend
            args:
                - VITE_CLIENT_ID=${VITE_CLIENT_ID}
                - VITE_API_URL=${VITE_API_URL}
                - VITE_AUTH_URL=${VITE_AUTH_URL}
        restart: always
        networks:
            - transcendence
        ports:
            - 4173:4173

    backend:
        image: backend
        container_name: backend
        build:
            context: ./srcs/backend
            args:
                - DATABASE_URL=${DATABASE_URL}
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - postgres
        env_file:
            - .env
        networks:
            - transcendence

networks:
    transcendence:
