version: "3.1"

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        env_file: .env
        networks:
            - transcendence
        expose:
            - "5432"

    frontend:
        image: frontend
        container_name: frontend
        build: ./srcs/frontend
        restart: always
        environment:
            - VITE_CLIENT_ID=${VITE_CLIENT_ID}
            - VITE_API_URL=${VITE_API_URL}
            - VITE_42_AUTH_URL=${VITE_42_AUTH_URL}
        networks:
            - transcendence
        ports:
            - "8080:8080"

    backend:
        image: backend
        container_name: backend
        build: ./srcs/backend
        restart: always
        env_file: .env
        networks:
            - transcendence
        depends_on:
            - postgres
        links:
            - postgres
        expose:
            - "3000"

networks:
    transcendence:
