version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    env_file: .env

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  frontend:
    image: frontend
    container_name: frontend
    build: ./srcs/frontend
    restart: always
    ports:
      - "443:443"

  backend:
    image: backend
    container_name: backend
    build: ./srcs/backend
    restart: always
    expose:
      - "3000"

networks:
  transcendence:
    driver: bridge

volumes:
  postgres:
